Fix build without --enable-bcrelay
When built without --enable-bcrelay,

bcrelay.c: In function 'showusage':
bcrelay.c:242:10: error: 'PIDFILE_BCRELAY_DEFAULT' undeclared (first use in this function)
          PIDFILE_BCRELAY_DEFAULT);
          ^~~~~~~~~~~~~~~~~~~~~~~

Regression introduced by 1dbf25a5b10df5abc16baf1095086100838ff34b.

Reported-by: mattias jonsson <mj@mjw.se>
Signed-off-by: James Cameron <quozl@laptop.org>